# Generated by Django 2.1 on 2020-07-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, verbose_name='Código de barras')),
                ('nombreCliente', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidosCliente', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('porcentaje', models.PositiveIntegerField(default=5, verbose_name='Porcentaje descuento')),
                ('saldoMonedero', models.FloatField(default=0.0, verbose_name='Saldo en monedero')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificacion', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
                ('estatus', models.PositiveIntegerField(default=1, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='PagoDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('importeTotal', models.FloatField(verbose_name='Importe total de venta')),
                ('porcentajePago', models.PositiveIntegerField(verbose_name='Porcentaje descuento del pago')),
                ('saldoClienteAnterior', models.FloatField(verbose_name='Saldo anterior de Cliente')),
                ('SaldoClienteFinal', models.FloatField(verbose_name='Saldo Final de Cliente')),
                ('importeEfectivoTarjeta', models.FloatField(verbose_name='Importe en efectivo o tarjeta C/D')),
                ('importeMonedeto', models.FloatField(verbose_name='Importe monedero eléctronico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
            ],
        ),
    ]
